version: '3.7'

services:
  redis:
    restart: always
  backend:
    restart: always
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile.production
    ports:
      - 80:80
      - 443:443
    links:
      - flask
    depends_on:
      - flask
    restart: always
